### ISSUE TITLE
Crash: removedChildren count (0) was not what we expected (1) in iOS

### ISSUE THREAD

**Issue by Amit-khatkar** [indiespirit/react-native-chart-kit#62] opened 2018-11-14 07:12 UTC
I am using LineChart with bezier and its working fine in android but showing error
in iOS. App is getting data from firebase then it updates the states. chart renders correctly in android but crashes on ios

`<LineChart

    data={{
      labels: this.state.chartLable,
      datasets: [{
        data: this.state.chartData
      }]
    }} 
    width={wp('96%')} 
    height={220}
    chartConfig={{
      backgroundColor: '#26d292',
      backgroundGradientFrom: '#22c393',
      backgroundGradientTo: '#22e093',
      decimalPlaces: 2, // optional, defaults to 2dp
      color: (opacity = 1) => `rgba(255, 255, 255, ${opacity})`,
      style: {
        borderRadius: 16,
      }
    }}
    bezier
    style={{
      marginVertical: 8,
      borderRadius: 16,
    }}
  />`

<img width="340" alt="screenshot 2018-11-14 at 12 31 08 pm" src="https://user-images.githubusercontent.com/16208872/48465570-42ed5580-e809-11e8-9c5c-1fb959d336aa.png">

**Comment by Amit-khatkar** [comment] 2018-12-08 11:49
> I got the same error and it was resolved when I used the following versions together:
> "react-native-chart-kit": "1.1.8",
> "react-native-svg": "6.2.2"

not working :(

**Comment by ankha0109** [comment] 2018-12-12 09:04
Same issue, Any idea ?

**Comment by under94** [comment] 2018-12-14 14:01
some issue

**Comment by cristian1703** [comment] 2018-12-18 19:03
try using "react-native-svg": "6.3.1" with "react-native-chart-kit": "^1.2.1"

**Comment by Hermanya** [comment] 2019-01-20 21:08
in the 2.0.0 release I wrapped all array renders into `<G>`s, this should be fixed now

**Closed by Hermanya** 2019-01-20 21:08 UTC

**Comment by msand** [comment] 2019-02-09 18:42
I've published a fix in v9.2.4 of react-native-svg, can you try with that?
The root cause is the Defs ViewManager returning nil for the shadowView, so the more efficient way to workaround this if you want backwards compatibility with pre v9.2.4 is to wrap the Defs elements in a G, rather then the dynamic content.
