### ISSUE TITLE
rendering issue in android

### ISSUE THREAD

**Issue by jintomon** [indiespirit/react-native-chart-kit#102] opened 2019-04-03 12:06 UTC
I am getting rendering issue in ANDROID devices, it is working in IOS though.

**React versions** ->
      react: 16.6.1
      react-native: 0.57.8

**Error description** ->
     TypeError: TypeError: TypeError: undefined is not a function (evaluating 'data.entries()[typeof Symbol === "function" ? Symbol.iterator : "@@iterator"]()')

As a temporary solution, I added "**import 'babel-polyfill**' which is not a good solution as it has more memory impact. Any other workaround available ?

**Comment by Hermanya** [comment] 2019-04-03 13:44
Try installing 'core-js' and importing `core-js/features/object/entries`, it has a lighter foot print.

**Comment by Hermanya** [comment] 2019-04-03 13:51
this is a duplicate of https://github.com/indiespirit/react-native-chart-kit/issues/29

**Closed by Hermanya** 2019-04-03 13:51 UTC
