### ISSUE TITLE
Don't see vertical labels in BarChart

### ISSUE THREAD

**Issue by choricao** [indiespirit/react-native-chart-kit#22] opened 2018-07-05 23:06 UTC
I created a BarChart according to the sample code. Everything looks good, but I cannot see vertical labels for y-axis. If I switched it to LineChart, vertical labels will show up. Any ideas why?

**Comment by Hermanya** [comment] 2018-07-06 02:03
This is a regression bug, which is now fixed.
Please update to the latest version.

**Closed by Hermanya** 2018-07-06 02:03 UTC

**Comment by gypsicoder** [comment] 2020-04-23 11:51
In my end in some devices horizontal labels are not showing if all the data is 0. Could someone tell the reason.
Here are the code snippets
```
let chartData = {
            labels:['4/15','4/16','4/17','4/18'],
            datasets: [{
                data:[0, 0, 0, 0],
            }],
        };

<BarChart
                            data={this.state.chartData} 
                            width={screenWidth-20}
                            withHorizontalLabels={true}
                            withVerticalLabels={true}
                            height={240}
                            fromZero={true}
                            showBarTops={false}
                            withInnerLines={false}
                            chartConfig={{
                                backgroundColor: '#F8F8F8',
                                backgroundGradientFrom: "#F8F8F8",
                                backgroundGradientTo: "#F8F8F8",
                                decimalPlaces: 0, 
                                color: (opacity = 1) => `rgba(250, 200, 30, 1)`,
                                labelColor:(opacity = 1) => '#373737',
                                style: {
                                    borderRadius: 16
                                },
                                barPercentage: 0.5,
                                fillShadowGradientOpacity: 1,
                            }}
                        />
```
